export { default as Index } from './index.vue'
export { default as ShopPage } from './Shop.vue'
export { default as SingleProduct } from './SingleProduct.vue'
export { default as CheckOut } from './CheckOut.vue'
export { default as OrderDone } from './OrderDone.vue'